# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-13 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='glossary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('words', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
