# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-16 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0005_auto_20181215_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('response', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=30)),
                ('aim', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='guessing_chat',
        ),
        migrations.RemoveField(
            model_name='room',
            name='questions_chat',
        ),
        migrations.AlterField(
            model_name='room',
            name='glossary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paint.Glossary'),
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paint.Room'),
        ),
    ]
