# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-17 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0014_auto_20181217_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='response',
            field=models.CharField(default='no_response', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='glossary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paint.Glossary'),
        ),
    ]
